# Configuration for deploying this project
# via Render Blueprints
services:
- type: web
  name: prometheus
  runtime: docker
  plan: starter
  disk:
    name: prometheus-disk
    mountPath: /var/data
    sizeGB: 1

  # Uncomment to scale the number of instances.
  # Requires enabling scaling for disk-backed services
  # in the Render Dashboard.
  #
  # numInstances: 2
